--- #YAML:1.0
name:                     CPAN-Testers-Data-Addresses
version:                  0.11
abstract:                 CPAN Testers Addresses Data Manager
author:
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  perl:                             5.006
  Class::Accessor::Fast:            0
  CPAN::Testers::Common::DBUtils:   0.08
  Config::IniFiles:                 0
  DBI:                              0
  DBD::mysql:                       0
  DBD::SQLite:                      0
  File::Basename:                   0
  File::Path:                       0
  File::Slurp:                      0
  Getopt::Long:                     0
  IO::File:                         0
recommends:
  Test::CPAN::Meta:                 0
  Test::CPAN::Meta::JSON:           0
  Test::Database:                   0
  Test::Pod:                        1.00
  Test::Pod::Coverage:              0.08
build_requires:
  Test::More:                       0.70

provides:
  CPAN::Testers::Data::Addresses:
    file:     lib/CPAN/Testers/Data/Addresses.pm
    version:  0.11

no_index:
  directory:
    - t
    - examples

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  homepage:   http://stats.cpantesters.org
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=CPAN-Testers-Data-Addresses
  repository: http://github.com/barbie/cpan-testers-data-addresses

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
